server:
  port: 9091
spring:
  data:
#    连接mongodb配置
    mongodb:
      host: 172.27.159.36
      database: message
      port: 27017

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: abc8909389
    url: jdbc:mysql://localhost:3306/mysql_learn?serverTimezone=GMT%2B8&characterEncoding=utf8&useSSL=true
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
